# Competencia en Kaggle: Titanic: Machine Learning from Disaster

In [11]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
validate = pd.read_csv('gender_submission.csv')

# Drop features-... is this good?

In [12]:
train = train.drop(['Name' ,'Ticket' , 'Fare', 'Cabin', 'Embarked'],axis=1)
test = test.drop(['Name', 'Ticket' , 'Fare', 'Cabin', 'Embarked'],axis=1)

train.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch
0            1         0       3    male  22.0      1      0
1            2         1       1  female  38.0      1      0
2            3         1       3  female  26.0      0      0
3            4         1       1  female  35.0      1      0
4            5         0       3    male  35.0      0      0
5            6         0       3    male   NaN      0      0
6            7         0       1    male  54.0      0      0
7            8         0       3    male   2.0      3      1
8            9         1       3  female  27.0      0      2
9           10         1       2  female  14.0      1      0

# Sex mapping 1 - male, 0 - female

In [13]:
train['Sex_binary']=train['Sex'].map({'male':1,'female':0})
test['Sex_binary']=test['Sex'].map({'male':1,'female':0})


# Age cleaning

In [14]:

train['Age'] = train['Age'].fillna(0)
test['Age'] = test['Age'].fillna(0)

averageAgeTrain= sum(train['Age']) / len(train['Age']) 
averageAgeTest= sum( test['Age']) / len(test['Age']) 

for i in range(0, len(train['Age'])):
    if(train['Age'][i] == 0):
        train['Age'][i] = averageAgeTrain
        
for i in range(0, len(test['Age'])):
    if(test['Age'][i] == 0):
        test['Age'][i] = averageAgeTest     

C:\Users\vilo_\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\vilo_\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [15]:
features = ['Pclass','Age','Sex_binary']
target = 'Survived'

In [16]:
train[features].head(3)

Pclass   Age  Sex_binary
0       3  22.0           1
1       1  38.0           0
2       3  26.0           0

In [17]:
import numpy as np

In [18]:
X_train = np.array(train[features])
X_train

array([[ 3.        , 22.        ,  1.        ],
       [ 1.        , 38.        ,  0.        ],
       [ 3.        , 26.        ,  0.        ],
       ...,
       [ 3.        , 23.79929293,  0.        ],
       [ 1.        , 26.        ,  1.        ],
       [ 3.        , 32.        ,  1.        ]])

In [19]:
y_train = np.array(train[target])
y_train = y_train.reshape(-1,1)
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [146]:
# Import keras modules
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.initializers import glorot_normal
from keras import optimizers


In [147]:
out_dimension = 1
nHidden = 20
nInputDimensions = X_train.shape[1]

model = Sequential()
model.add(Dense(nHidden, input_dim=nInputDimensions, activation='elu', kernel_initializer=glorot_normal(seed=0)))

for i in range(0, 7): # capas
    model.add(Dense(nHidden, activation='elu', kernel_initializer=glorot_normal(seed=0))) # agregar capa
    
#model.add(Activation('softmax'))
model.add(Dense(out_dimension, activation='sigmoid', kernel_initializer=glorot_normal(seed=0)))

#model.add(Dense(1, input_dim=3, activation='relu', kernel_initializer="uniform"))
#model.add(Dense(1, activation='sigmoid', kernel_initializer="uniform"))



model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [148]:
model.fit(X_train, y_train, epochs=400, batch_size=1)

Epoch 1/400
891/891 [==============================] - 4s 4ms/step - loss: 0.6754 - acc: 0.6150
Epoch 2/400
891/891 [==============================] - 2s 2ms/step - loss: 0.6231 - acc: 0.6655
Epoch 3/400
891/891 [==============================] - 2s 2ms/step - loss: 0.5184 - acc: 0.7666
Epoch 4/400
891/891 [==============================] - 2s 2ms/step - loss: 0.5082 - acc: 0.7710
Epoch 5/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4922 - acc: 0.7789
Epoch 6/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4858 - acc: 0.7755
Epoch 7/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4764 - acc: 0.7912
Epoch 8/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4735 - acc: 0.7890
Epoch 9/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4782 - acc: 0.7767
Epoch 10/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4782 - acc: 0.7789
Epoch 11/400
891/891 [=================

891/891 [==============================] - 2s 3ms/step - loss: 0.4249 - acc: 0.7946
Epoch 86/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4171 - acc: 0.8002
Epoch 87/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4245 - acc: 0.8070
Epoch 88/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4269 - acc: 0.7957
Epoch 89/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4261 - acc: 0.7991
Epoch 90/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4264 - acc: 0.8081
Epoch 91/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4247 - acc: 0.8070
Epoch 92/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4190 - acc: 0.8036
Epoch 93/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4215 - acc: 0.8070
Epoch 94/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4381 - acc: 0.7912
Epoch 95/400
891/891 [=====================

891/891 [==============================] - 2s 2ms/step - loss: 0.4128 - acc: 0.8171
Epoch 169/400
891/891 [==============================] - 2s 3ms/step - loss: 0.4092 - acc: 0.8070
Epoch 170/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4117 - acc: 0.8137
Epoch 171/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4111 - acc: 0.8193
Epoch 172/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4158 - acc: 0.8148
Epoch 173/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4076 - acc: 0.8070
Epoch 174/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4154 - acc: 0.8148
Epoch 175/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4159 - acc: 0.8025
Epoch 176/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4124 - acc: 0.8058
Epoch 177/400
891/891 [==============================] - 2s 3ms/step - loss: 0.4218 - acc: 0.8081
Epoch 178/400
891/891 [===========

891/891 [==============================] - 2s 2ms/step - loss: 0.4055 - acc: 0.8137
Epoch 252/400
891/891 [==============================] - 2s 2ms/step - loss: 0.3984 - acc: 0.8182
Epoch 253/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4119 - acc: 0.8171
Epoch 254/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4044 - acc: 0.8238
Epoch 255/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4162 - acc: 0.8070
Epoch 256/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4111 - acc: 0.8025
Epoch 257/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4048 - acc: 0.8058
Epoch 258/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4023 - acc: 0.8182
Epoch 259/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4306 - acc: 0.8092
Epoch 260/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4192 - acc: 0.8025
Epoch 261/400
891/891 [===========

891/891 [==============================] - 2s 2ms/step - loss: 0.4289 - acc: 0.8047
Epoch 335/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4602 - acc: 0.8047
Epoch 336/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4311 - acc: 0.8025
Epoch 337/400
891/891 [==============================] - 2s 3ms/step - loss: 0.4156 - acc: 0.8114
Epoch 338/400
891/891 [==============================] - 2s 3ms/step - loss: 0.4129 - acc: 0.8148
Epoch 339/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4100 - acc: 0.8137
Epoch 340/400
891/891 [==============================] - 2s 3ms/step - loss: 0.4134 - acc: 0.8193
Epoch 341/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4104 - acc: 0.8103
Epoch 342/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4181 - acc: 0.8227
Epoch 343/400
891/891 [==============================] - 2s 2ms/step - loss: 0.4176 - acc: 0.8025
Epoch 344/400
891/891 [===========

In [149]:
X_test = np.array(test[features])
X_test

array([[ 3.        , 34.5       ,  1.        ],
       [ 3.        , 47.        ,  0.        ],
       [ 2.        , 62.        ,  1.        ],
       ...,
       [ 3.        , 38.5       ,  1.        ],
       [ 3.        , 24.04425837,  1.        ],
       [ 3.        , 24.04425837,  1.        ]])

In [150]:
predicciones = model.predict(X_test)
print(predicciones)


[[0.11193237]
 [0.27166632]
 [0.12565412]
 [0.11175375]
 [0.4989269 ]
 [0.14874938]
 [0.45316178]
 [0.11550937]
 [0.5011549 ]
 [0.11153197]
 [0.11167694]
 [0.30168706]
 [0.97606647]
 [0.1251332 ]
 [0.9683658 ]
 [0.9295218 ]
 [0.11671386]
 [0.11153197]
 [0.4880464 ]
 [0.2805079 ]
 [0.2583966 ]
 [0.2532159 ]
 [0.97604024]
 [0.2804327 ]
 [0.96731657]
 [0.11188403]
 [0.97608757]
 [0.11161278]
 [0.3565468 ]
 [0.11167694]
 [0.12254866]
 [0.11555303]
 [0.38553324]
 [0.49680746]
 [0.49924928]
 [0.11157764]
 [0.49680746]
 [0.49958846]
 [0.11169253]
 [0.11167694]
 [0.1119108 ]
 [0.49780077]
 [0.11190255]
 [0.91258967]
 [0.9703686 ]
 [0.11169253]
 [0.30623415]
 [0.11167694]
 [0.9519488 ]
 [0.3254663 ]
 [0.4977358 ]
 [0.11518051]
 [0.94204473]
 [0.97588646]
 [0.11557888]
 [0.26465112]
 [0.11193606]
 [0.11169253]
 [0.11167694]
 [0.97498417]
 [0.11235177]
 [0.11499505]
 [0.11169326]
 [0.4989269 ]
 [0.92739975]
 [0.9293877 ]
 [0.5011549 ]
 [0.29814115]
 [0.49866498]
 [0.9519488 ]
 [0.49687228]
 [0.11

In [151]:
predicciones = predicciones.tolist()

In [152]:
pre = pd.Series(predicciones)
validate['prediccion'] = pre
validate['prediccion'] = validate['prediccion'].str.get(0)
validate

PassengerId  Survived  prediccion  final
0            892         0    0.111932      0
1            893         1    0.271666      0
2            894         0    0.125654      0
3            895         0    0.111754      0
4            896         1    0.498927      1
5            897         0    0.148749      0
6            898         1    0.453162      1
7            899         0    0.115509      0
8            900         1    0.501155      1
9            901         0    0.111532      0
10           902         0    0.111677      0
11           903         0    0.301687      0
12           904         1    0.976066      1
13           905         0    0.125133      0
14           906         1    0.968366      1
15           907         1    0.929522      1
16           908         0    0.116714      0
17           909         0    0.111532      0
18           910         1    0.488046      1
19           911         1    0.280508      0
20           912         0    0.258397      0
21           913         0    0.253216      0
22           914         1    0.976040      1
23           915         0    0.280433      0
24           916         1    0.967317      1
25           917         0    0.111884      0
26           918         1    0.976088      1
27           919         0    0.111613      0
28           920         0    0.356547      0
29           921         0    0.111677      0
..           ...       ...         ...    ...
388         1280         0    0.111532      0
389         1281         0    0.346075      0
390         1282         0    0.495220      0
391         1283         1    0.963968      1
392         1284         0    0.221732      0
393         1285         0    0.119460      0
394         1286         0    0.111817      0
395         1287         1    0.976145      1
396         1288         0    0.111676      0
397         1289         1    0.967317      1
398         1290         0    0.111585      0
399         1291         0    0.111875      0
400         1292         1    0.975760      1
401         1293         0    0.116192      0
402         1294         1    0.976088      1
403         1295         0    0.257395      0
404         1296         0    0.321918      0
405         1297         0    0.114188      0
406         1298         0    0.114629      0
407         1299         0    0.289237      0
408         1300         1    0.496807      1
409         1301         1    0.295278      1
410         1302         1    0.496807      1
411         1303         1    0.974758      1
412         1304         1    0.481009      1
413         1305         0    0.111677      0
414         1306         1    0.974169      1
415         1307         0    0.111917      0
416         1308         0    0.111677      0
417         1309         0    0.111677      0

[418 rows x 4 columns]

In [153]:
coincidencias = []
for dato in validate.prediccion:
    if dato >= 0.5:
        coincidencias.append(1)
    else:
        coincidencias.append(0)
validate['final'] = coincidencias
validate

PassengerId  Survived  prediccion  final
0            892         0    0.111932      0
1            893         1    0.271666      0
2            894         0    0.125654      0
3            895         0    0.111754      0
4            896         1    0.498927      0
5            897         0    0.148749      0
6            898         1    0.453162      0
7            899         0    0.115509      0
8            900         1    0.501155      1
9            901         0    0.111532      0
10           902         0    0.111677      0
11           903         0    0.301687      0
12           904         1    0.976066      1
13           905         0    0.125133      0
14           906         1    0.968366      1
15           907         1    0.929522      1
16           908         0    0.116714      0
17           909         0    0.111532      0
18           910         1    0.488046      0
19           911         1    0.280508      0
20           912         0    0.258397      0
21           913         0    0.253216      0
22           914         1    0.976040      1
23           915         0    0.280433      0
24           916         1    0.967317      1
25           917         0    0.111884      0
26           918         1    0.976088      1
27           919         0    0.111613      0
28           920         0    0.356547      0
29           921         0    0.111677      0
..           ...       ...         ...    ...
388         1280         0    0.111532      0
389         1281         0    0.346075      0
390         1282         0    0.495220      0
391         1283         1    0.963968      1
392         1284         0    0.221732      0
393         1285         0    0.119460      0
394         1286         0    0.111817      0
395         1287         1    0.976145      1
396         1288         0    0.111676      0
397         1289         1    0.967317      1
398         1290         0    0.111585      0
399         1291         0    0.111875      0
400         1292         1    0.975760      1
401         1293         0    0.116192      0
402         1294         1    0.976088      1
403         1295         0    0.257395      0
404         1296         0    0.321918      0
405         1297         0    0.114188      0
406         1298         0    0.114629      0
407         1299         0    0.289237      0
408         1300         1    0.496807      0
409         1301         1    0.295278      0
410         1302         1    0.496807      0
411         1303         1    0.974758      1
412         1304         1    0.481009      0
413         1305         0    0.111677      0
414         1306         1    0.974169      1
415         1307         0    0.111917      0
416         1308         0    0.111677      0
417         1309         0    0.111677      0

[418 rows x 4 columns]

In [154]:
coincide = 0
coincide = sum(validate['Survived'] == validate['final'])
print(coincide/ len(validate))


match = 0
nomatch = 0
for val in validate.values:
    if val[1] == val[3]:
        match = match +1
    else:
        nomatch = nomatch +1
print(match/len(validate))

0.8444976076555024
0.8444976076555024


In [155]:
toKaggle = pd.DataFrame({'PassengerId':validate['PassengerId'],
                         'Survived':validate['final']})

toKaggle.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

# output file with your prediction

In [156]:
from datetime import datetime
archivo = 'Titanic01_'+ str(datetime.now().strftime('%Y-%m-%d'))+'.csv'

toKaggle.to_csv(archivo,index=False)

print('Creado: ' + archivo)

Creado: Titanic01_2018-10-27.csv
