# Competencia en Kaggle: Titanic: Machine Learning from Disaster

# 1. Crea una cuenta en Kaggle https://www.kaggle.com/

# 2. Ejecuta las celdas 

In [80]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
validate = pd.read_csv('gender_submission.csv')

# Drop features-... is this good?

In [81]:
train = train.drop(['Name','SibSp', 'Ticket' ,'Cabin', 'Embarked'],axis=1)
test = test.drop(['Name','SibSp', 'Ticket' , 'Cabin', 'Embarked'],axis=1)

train.head(10)

PassengerId  Survived  Pclass     Sex   Age  Parch     Fare
0            1         0       3    male  22.0      0   7.2500
1            2         1       1  female  38.0      0  71.2833
2            3         1       3  female  26.0      0   7.9250
3            4         1       1  female  35.0      0  53.1000
4            5         0       3    male  35.0      0   8.0500
5            6         0       3    male   NaN      0   8.4583
6            7         0       1    male  54.0      0  51.8625
7            8         0       3    male   2.0      1  21.0750
8            9         1       3  female  27.0      2  11.1333
9           10         1       2  female  14.0      0  30.0708

# Sex mapping 1 - male, 0 - female

In [82]:
train['Sex_binary']=train['Sex'].map({'male':1,'female':0})
test['Sex_binary']=test['Sex'].map({'male':1,'female':0})


# Age cleaning

In [83]:

train['Age'] = train['Age'].fillna(0)
test['Age'] = test['Age'].fillna(0)

averageAgeTrain= sum(train['Age']) / len(train['Age']) 
averageAgeTest= sum( test['Age']) / len(test['Age']) 

for i in range(0, len(train['Age'])):
    if(train['Age'][i] == 0):
        train['Age'][i] = averageAgeTrain
        
for i in range(0, len(test['Age'])):
    if(test['Age'][i] == 0):
        test['Age'][i] = averageAgeTest     

C:\Users\vilo_\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\vilo_\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [84]:
features = ['Pclass','Age','Sex_binary']
target = 'Survived'

In [85]:
train[features].head(3)

Pclass   Age  Sex_binary
0       3  22.0           1
1       1  38.0           0
2       3  26.0           0

In [86]:
import numpy as np

In [87]:
X_train = np.array(train[features])
X_train

array([[ 3.        , 22.        ,  1.        ],
       [ 1.        , 38.        ,  0.        ],
       [ 3.        , 26.        ,  0.        ],
       ...,
       [ 3.        , 23.79929293,  0.        ],
       [ 1.        , 26.        ,  1.        ],
       [ 3.        , 32.        ,  1.        ]])

In [88]:
y_train = np.array(train[target])
y_train = y_train.reshape(-1,1)
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [89]:
# Import keras modules
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import glorot_normal

In [90]:
out_dimension = 1
nHidden = 20
nInputDimensions = X_train.shape[1]

model = Sequential()
model.add(Dense(nHidden, input_dim=nInputDimensions, activation='elu', kernel_initializer=glorot_normal(seed=0)))

for i in range(0, 7): # capas
    model.add(Dense(nHidden, activation='elu', kernel_initializer=glorot_normal(seed=0))) # agregar capa

model.add(Dense(out_dimension, activation='sigmoid', kernel_initializer=glorot_normal(seed=0)))

#model.add(Dense(1, input_dim=3, activation='relu', kernel_initializer="uniform"))
#model.add(Dense(1, activation='sigmoid', kernel_initializer="uniform"))


model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [91]:
model.fit(X_train, y_train, epochs=400, batch_size=10)

Epoch 1/400
891/891 [==============================] - 2s 2ms/step - loss: 0.6450 - acc: 0.6375
Epoch 2/400
891/891 [==============================] - 0s 187us/step - loss: 0.5823 - acc: 0.6992
Epoch 3/400
891/891 [==============================] - 0s 180us/step - loss: 0.5045 - acc: 0.7497
Epoch 4/400
891/891 [==============================] - 0s 185us/step - loss: 0.5383 - acc: 0.7363
Epoch 5/400
891/891 [==============================] - 0s 209us/step - loss: 0.4650 - acc: 0.7912
Epoch 6/400
891/891 [==============================] - 0s 209us/step - loss: 0.4980 - acc: 0.7654
Epoch 7/400
891/891 [==============================] - 0s 199us/step - loss: 0.4595 - acc: 0.7980
Epoch 8/400
891/891 [==============================] - 0s 209us/step - loss: 0.4646 - acc: 0.7879
Epoch 9/400
891/891 [==============================] - 0s 190us/step - loss: 0.4700 - acc: 0.7834
Epoch 10/400
891/891 [==============================] - 0s 221us/step - loss: 0.4791 - acc: 0.7778
Epoch 11/400
891/891 

891/891 [==============================] - 0s 193us/step - loss: 0.4181 - acc: 0.8182
Epoch 84/400
891/891 [==============================] - 0s 189us/step - loss: 0.4083 - acc: 0.8148
Epoch 85/400
891/891 [==============================] - 0s 187us/step - loss: 0.4187 - acc: 0.8025
Epoch 86/400
891/891 [==============================] - 0s 201us/step - loss: 0.4196 - acc: 0.7980
Epoch 87/400
891/891 [==============================] - 0s 197us/step - loss: 0.4121 - acc: 0.8081
Epoch 88/400
891/891 [==============================] - 0s 189us/step - loss: 0.4124 - acc: 0.8193
Epoch 89/400
891/891 [==============================] - 0s 184us/step - loss: 0.4135 - acc: 0.8171
Epoch 90/400
891/891 [==============================] - 0s 193us/step - loss: 0.4117 - acc: 0.8148
Epoch 91/400
891/891 [==============================] - 0s 197us/step - loss: 0.4361 - acc: 0.8047
Epoch 92/400
891/891 [==============================] - 0s 186us/step - loss: 0.4185 - acc: 0.8171
Epoch 93/400
891/891 [=

891/891 [==============================] - 0s 170us/step - loss: 0.4067 - acc: 0.8260
Epoch 166/400
891/891 [==============================] - 0s 167us/step - loss: 0.4002 - acc: 0.8193
Epoch 167/400
891/891 [==============================] - 0s 168us/step - loss: 0.3993 - acc: 0.8283
Epoch 168/400
891/891 [==============================] - 0s 179us/step - loss: 0.4086 - acc: 0.8126
Epoch 169/400
891/891 [==============================] - 0s 180us/step - loss: 0.4210 - acc: 0.8013
Epoch 170/400
891/891 [==============================] - 0s 191us/step - loss: 0.4187 - acc: 0.8126
Epoch 171/400
891/891 [==============================] - 0s 175us/step - loss: 0.4028 - acc: 0.8114
Epoch 172/400
891/891 [==============================] - 0s 175us/step - loss: 0.4158 - acc: 0.8047
Epoch 173/400
891/891 [==============================] - 0s 224us/step - loss: 0.4120 - acc: 0.8092
Epoch 174/400
891/891 [==============================] - 0s 224us/step - loss: 0.4052 - acc: 0.8182
Epoch 175/400


891/891 [==============================] - 0s 184us/step - loss: 0.4000 - acc: 0.8215
Epoch 248/400
891/891 [==============================] - 0s 167us/step - loss: 0.4011 - acc: 0.8171
Epoch 249/400
891/891 [==============================] - 0s 168us/step - loss: 0.3958 - acc: 0.8182
Epoch 250/400
891/891 [==============================] - 0s 181us/step - loss: 0.4028 - acc: 0.8159
Epoch 251/400
891/891 [==============================] - 0s 228us/step - loss: 0.3995 - acc: 0.8182
Epoch 252/400
891/891 [==============================] - 0s 222us/step - loss: 0.4051 - acc: 0.8137
Epoch 253/400
891/891 [==============================] - 0s 196us/step - loss: 0.3983 - acc: 0.8137
Epoch 254/400
891/891 [==============================] - 0s 221us/step - loss: 0.4029 - acc: 0.8272
Epoch 255/400
891/891 [==============================] - 0s 225us/step - loss: 0.4042 - acc: 0.8204
Epoch 256/400
891/891 [==============================] - 0s 188us/step - loss: 0.4007 - acc: 0.8182
Epoch 257/400


891/891 [==============================] - 0s 179us/step - loss: 0.3834 - acc: 0.8272
Epoch 330/400
891/891 [==============================] - 0s 167us/step - loss: 0.3880 - acc: 0.8283
Epoch 331/400
891/891 [==============================] - 0s 171us/step - loss: 0.3993 - acc: 0.8272
Epoch 332/400
891/891 [==============================] - 0s 169us/step - loss: 0.3942 - acc: 0.8249
Epoch 333/400
891/891 [==============================] - 0s 165us/step - loss: 0.3884 - acc: 0.8294
Epoch 334/400
891/891 [==============================] - 0s 171us/step - loss: 0.3855 - acc: 0.8204
Epoch 335/400
891/891 [==============================] - 0s 176us/step - loss: 0.3896 - acc: 0.8215
Epoch 336/400
891/891 [==============================] - 0s 177us/step - loss: 0.3866 - acc: 0.8238
Epoch 337/400
891/891 [==============================] - 0s 172us/step - loss: 0.3868 - acc: 0.8204
Epoch 338/400
891/891 [==============================] - 0s 171us/step - loss: 0.3816 - acc: 0.8328
Epoch 339/400


In [92]:
X_test = np.array(test[features])
X_test

array([[ 3.        , 34.5       ,  1.        ],
       [ 3.        , 47.        ,  0.        ],
       [ 2.        , 62.        ,  1.        ],
       ...,
       [ 3.        , 38.5       ,  1.        ],
       [ 3.        , 24.04425837,  1.        ],
       [ 3.        , 24.04425837,  1.        ]])

In [93]:
predicciones = model.predict(X_test)
print(predicciones)


[[0.16599362]
 [0.01399665]
 [0.06946304]
 [0.18148686]
 [0.54469144]
 [0.11275396]
 [0.5214501 ]
 [0.12411314]
 [0.5500999 ]
 [0.11129651]
 [0.12736952]
 [0.3747315 ]
 [0.9718008 ]
 [0.06537109]
 [0.98102516]
 [0.8845061 ]
 [0.09868813]
 [0.11129651]
 [0.534189  ]
 [0.01103967]
 [0.2605601 ]
 [0.29184005]
 [0.968002  ]
 [0.2137211 ]
 [0.97807294]
 [0.05420535]
 [0.9797528 ]
 [0.11655738]
 [0.4362905 ]
 [0.12736952]
 [0.07967978]
 [0.1132483 ]
 [0.5056114 ]
 [0.54183483]
 [0.51731056]
 [0.10702462]
 [0.54183483]
 [0.54591674]
 [0.14004575]
 [0.12736952]
 [0.07072645]
 [0.32879212]
 [0.06503093]
 [0.9104186 ]
 [0.9859228 ]
 [0.14004575]
 [0.3864732 ]
 [0.12736952]
 [0.9708791 ]
 [0.4757326 ]
 [0.32646614]
 [0.13310093]
 [0.9987099 ]
 [0.9740248 ]
 [0.11341693]
 [0.17334832]
 [0.14492708]
 [0.14004575]
 [0.12736952]
 [0.9913421 ]
 [0.10617054]
 [0.14406177]
 [0.10654929]
 [0.54469144]
 [0.94847214]
 [0.88367885]
 [0.5500999 ]
 [0.3631652 ]
 [0.51932466]
 [0.9708791 ]
 [0.54190767]
 [0.11

In [94]:
predicciones = predicciones.tolist()

In [95]:
pre = pd.Series(predicciones)
validate['prediccion'] = pre
validate['prediccion'] = validate['prediccion'].str.get(0)
validate

PassengerId  Survived  prediccion
0            892         0    0.165994
1            893         1    0.013997
2            894         0    0.069463
3            895         0    0.181487
4            896         1    0.544691
5            897         0    0.112754
6            898         1    0.521450
7            899         0    0.124113
8            900         1    0.550100
9            901         0    0.111297
10           902         0    0.127370
11           903         0    0.374732
12           904         1    0.971801
13           905         0    0.065371
14           906         1    0.981025
15           907         1    0.884506
16           908         0    0.098688
17           909         0    0.111297
18           910         1    0.534189
19           911         1    0.011040
20           912         0    0.260560
21           913         0    0.291840
22           914         1    0.968002
23           915         0    0.213721
24           916         1    0.978073
25           917         0    0.054205
26           918         1    0.979753
27           919         0    0.116557
28           920         0    0.436291
29           921         0    0.127370
..           ...       ...         ...
388         1280         0    0.111297
389         1281         0    0.307006
390         1282         0    0.279237
391         1283         1    0.967967
392         1284         0    0.121316
393         1285         0    0.080283
394         1286         0    0.193291
395         1287         1    0.998440
396         1288         0    0.126933
397         1289         1    0.978073
398         1290         0    0.114383
399         1291         0    0.198565
400         1292         1    0.979472
401         1293         0    0.086501
402         1294         1    0.979753
403         1295         0    0.356730
404         1296         0    0.410469
405         1297         0    0.105645
406         1298         0    0.109843
407         1299         0    0.328640
408         1300         1    0.541835
409         1301         1    0.235062
410         1302         1    0.541835
411         1303         1    0.992142
412         1304         1    0.530154
413         1305         0    0.127370
414         1306         1    0.992862
415         1307         0    0.073315
416         1308         0    0.127370
417         1309         0    0.127370

[418 rows x 3 columns]

In [96]:
coincidencias = []
for dato in validate.prediccion:
    if dato >= 0.5:
        coincidencias.append(1)
    else:
        coincidencias.append(0)
validate['final'] = coincidencias
validate

PassengerId  Survived  prediccion  final
0            892         0    0.165994      0
1            893         1    0.013997      0
2            894         0    0.069463      0
3            895         0    0.181487      0
4            896         1    0.544691      1
5            897         0    0.112754      0
6            898         1    0.521450      1
7            899         0    0.124113      0
8            900         1    0.550100      1
9            901         0    0.111297      0
10           902         0    0.127370      0
11           903         0    0.374732      0
12           904         1    0.971801      1
13           905         0    0.065371      0
14           906         1    0.981025      1
15           907         1    0.884506      1
16           908         0    0.098688      0
17           909         0    0.111297      0
18           910         1    0.534189      1
19           911         1    0.011040      0
20           912         0    0.260560      0
21           913         0    0.291840      0
22           914         1    0.968002      1
23           915         0    0.213721      0
24           916         1    0.978073      1
25           917         0    0.054205      0
26           918         1    0.979753      1
27           919         0    0.116557      0
28           920         0    0.436291      0
29           921         0    0.127370      0
..           ...       ...         ...    ...
388         1280         0    0.111297      0
389         1281         0    0.307006      0
390         1282         0    0.279237      0
391         1283         1    0.967967      1
392         1284         0    0.121316      0
393         1285         0    0.080283      0
394         1286         0    0.193291      0
395         1287         1    0.998440      1
396         1288         0    0.126933      0
397         1289         1    0.978073      1
398         1290         0    0.114383      0
399         1291         0    0.198565      0
400         1292         1    0.979472      1
401         1293         0    0.086501      0
402         1294         1    0.979753      1
403         1295         0    0.356730      0
404         1296         0    0.410469      0
405         1297         0    0.105645      0
406         1298         0    0.109843      0
407         1299         0    0.328640      0
408         1300         1    0.541835      1
409         1301         1    0.235062      0
410         1302         1    0.541835      1
411         1303         1    0.992142      1
412         1304         1    0.530154      1
413         1305         0    0.127370      0
414         1306         1    0.992862      1
415         1307         0    0.073315      0
416         1308         0    0.127370      0
417         1309         0    0.127370      0

[418 rows x 4 columns]

In [97]:
coincide = 0
coincide = sum(validate['Survived'] == validate['final'])
print(coincide/ len(validate))


match = 0
nomatch = 0
for val in validate.values:
    if val[1] == val[3]:
        match = match +1
    else:
        nomatch = nomatch +1
print(match/len(validate))

0.9354066985645934
0.9354066985645934


In [98]:
toKaggle = pd.DataFrame({'PassengerId':validate['PassengerId'],
                         'Survived':validate['final']})

toKaggle.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

# output file with your prediction

In [99]:
from datetime import datetime
archivo = 'Titanic01_'+ str(datetime.now().strftime('%Y-%m-%d'))+'.csv'

toKaggle.to_csv(archivo,index=False)

print('Creado: ' + archivo)

Creado: Titanic01_2018-10-27.csv
